version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aadi7525
      POSTGRES_DB: school_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask-app:
    image: cyberleafy/flask-school-app:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:aadi7525@db:5432/school_db

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --url http://flask-app:8000
    depends_on:
      - flask-app

volumes:
  pgdata:
